---
# ---------------------------------------------------------
# Called by other roles to register a host with SkyDNS
# ---------------------------------------------------------
- debug: msg="Sending registration request to '{{ etcd_host }}' for '{{ fqdn }}' => '{{ ip }}'"
- debug: var=etcd_host
- debug: var=etcd_port
- debug: var=skydns_host
- debug: var=fqdn
- debug: var=ip

- set_fact:
    registration_url: "http://{{ etcd_host }}:{{ etcd_port }}/v2/keys/skydns/{{ '/'.join( fqdn.split( '.' )[::-1] ) }}"
- set_fact:
    registration_command: "curl -XPUT '{{ registration_url }}' -d value='{ \"host\" : \"{{ ip }}\" }'"

- debug: msg="Running '{{ registration_command }}'"

- name:    Sending registration request
  command: "{{ registration_command }}"

  # https://github.com/ansible/ansible-modules-core/issues/265
  # uri:
  #   method:  POST
  #   url:     "{{ registration_url }}"
  #   body:    "{ 'host' : '{{ ip }}' }"
  #   timeout: 3

- name:     Running dig
  command:  dig @{{ skydns_host }} '{{ fqdn }}'
  register: dig_out

- name: Verifying dig
  assert:
    that:
      - "'{{ fqdn }}' in dig_out.stdout"
      - "'{{ ip }}'   in dig_out.stdout"
