---
tomcat: {
  version: latest, # 8.0.17, 7.0.57, latest - https://tomcat.apache.org/download-80.cgi
  port:    8080,
  latest: {
    command: "curl -Ls '{{ common.urls.tomcat }}/download-80.cgi' | grep 'apache-tomcat-' | grep '.zip' | head -1 | sed -r 's/.+apache-tomcat-//' | sed -r 's/\\.zip.+//'",
    pattern: '^\d+\.\d+\.\d+$'
  },
  url:     'http://www.eu.apache.org/dist/tomcat/tomcat-<N>/v<version>/bin/apache-tomcat-<version>.tar.gz',
  archive: /opt/tomcat-<version>.tar.gz,
  home:    /opt/tomcat
}
