---
ubuntu: {
  apt_repo:     'http://ubuntu.mirror.su.se/ubuntu', # http://mirrors.ubuntu.com/mirrors.txt
  root_home:    /root,
  home_dir:     /home,
  bash:         /bin/bash,
  log_dir:      /var/log,
  pid_dir:      /var/run,
  env_file:     /etc/environment,
  init_dir:     /etc/init,
  envs_dir:     /etc/profile.d, # http://goo.gl/ksHX6N
  bin_dir:      /usr/bin,
  local_dir:    /usr/local,
  sudoers:      /etc/sudoers,
  sources_list: /etc/apt/sources.list,
  etc_default:  /etc/default,
  resolv_conf:  /etc/resolv.conf
}
