---
# --------------------------------------------
#   Common tasks for Helios master and agent
# --------------------------------------------
- debug: msg="helios_master = '{{ helios_master }}'"
- debug: msg="helios_master_port = '{{ helios_master_port }}'"
- debug: msg="zookeeper_port = '{{ zookeeper_port }}'"
- debug: msg="etcd_port = '{{ etcd_port }}'"
- debug: msg="exhibitor_port = '{{ exhibitor_port }}'"
- debug: msg="skydns_domain = '{{ skydns_domain }}'"
- debug: msg="ansible_fqdn = '{{ ansible_fqdn }}'"
- debug: msg="facter_ipaddress_eth1 = '{{ facter_ipaddress_eth1 }}'"

- include: "{{ common.utils.fake }}"
  vars:
    # We have Java 8 JRE installed already
    package: java7-runtime

- name: Calculating Helios version
  set_fact:
    helios_version:     "{{ helios.version     | calculate( helios.latest ) }}"
    helios_master_port: "{{ helios_master_port | default( helios.master.port ) }}"

- include: "{{ common.utils.download }}"
  vars:
    title:   Helios
    url:     "{{ helios.url     | tokens({ 'version': helios_version }) }}"
    archive: "{{ helios.archive | tokens({ 'version': helios_version }) }}"
    home:    "{{ helios.home }}"

- name: Installing Helios services
  apt:  deb="{{ helios.home }}/helios-services_{{ helios_version }}_all.deb"
