---
# ---------------------------------------------
# Verifies connectivity with Helios master
# ---------------------------------------------
- debug: msg="Verifying Helios master '{{ master }}' endpoints"

- include: "{{ common.utils.verify }}"
  vars:
    title: Helios master DNS
    host:  "{{ master }}"
    port:  "{{ common.net.dns_port }}"

- include: "{{ common.utils.verify }}"
  vars:
    title: Helios master service
    host:  "{{ master }}"
    port:  "{{ helios_master_port }}"
    verify:
      - { status: 404 }

- include: "{{ common.utils.verify }}"
  vars:
    title: Helios master ZooKeeper
    host:  "{{ master }}"
    port:  "{{ zookeeper_port }}"

- include: "{{ common.utils.verify }}"
  vars:
    title: Helios master etcd
    host:  "{{ master }}"
    port:  "{{ etcd_port }}"
    verify:
      - { path: '/version', content: "{{ etcd.version }}" }

- include: "{{ common.utils.verify }}"
  vars:
    title: Helios master Exhibitor
    host:  "{{ master }}"
    port:  "{{ exhibitor_port }}"
    verify:
      - { path: /exhibitor/v1/ui/index.html, content: Exhibitor for ZooKeeper }

- include: "{{ playbook_dir }}/roles/skydns/register-host.yml"
  vars:
    etcd_host:   "{{ master }}"
    skydns_host: "{{ master }}"
    fqdn:        "{{ ansible_fqdn }}"
    ip:          "{{ facter_ipaddress_eth1 }}"
