---
- name: Calculating Artifactory version
  set_fact:
    artifactory_version: "{{ artifactory.version | calculate( artifactory.latest ) }}"
- set_fact:
    artifactory_port:    "{{ artifactory_port    | default( artifactory.port ) }}"

  # -----------------------
  # Standalone
  # -----------------------

- set_fact:
    artifactory_home:    "{{ artifactory.standalone.home }}/artifactory-{{ artifactory_version }}"
  when: artifactory.run == 'standalone'

- include: "{{ common.utils.service }}"
  vars:
    service: artifactory
    title:   Artifactory
    url:     "{{ artifactory.standalone.url     | tokens({ 'version': artifactory_version }) }}"
    archive: "{{ artifactory.standalone.archive | tokens({ 'version': artifactory_version }) }}"
    home:    "{{ artifactory.standalone.home }}"
    configs:
      - { from: server.xml, to: "{{ artifactory_home }}/tomcat/conf/server.xml" }
    command: "{{ artifactory_home }}/bin/artifactory.sh"
    port:    "{{ artifactory_port }}"
    timeout: "{{ artifactory.timeout }}"
    wait:    "{{ artifactory.wait }}"
    verify:  "{{ artifactory.verify }}"
  when: artifactory.run == 'standalone'

  # -----------------------
  # War
  # -----------------------

- include: "{{ common.utils.tomcat }}"
  vars:
    tomcat_port: "{{ artifactory_port }}"
  when: artifactory.run == 'war'

- include: "{{ common.utils.service }}"
  vars:
    service: artifactory
    title:   Artifactory
    url:     "{{ artifactory.war.url     | tokens({ 'version': artifactory_version }) }}"
    archive: "{{ artifactory.war.archive | tokens({ 'version': artifactory_version }) }}"
    home:    "{{ tomcat_webapps }}/{{ artifactory.war.home }}"
    command: "{{ tomcat_run  }}"
    port:    "{{ artifactory_port }}"
    timeout: "{{ artifactory.timeout }}"
    wait:    "{{ artifactory.wait }}"
    verify:  "{{ artifactory.verify }}"
  when: artifactory.run == 'war'
