---
# http://docs.docker.com/installation/ubuntulinux/

- name:    Adding Docker repository key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name:           Adding Docker repository
  apt_repository: repo='deb https://get.docker.io/ubuntu docker main' update_cache=yes

- name: Installing Docker
  apt:  name=lxc-docker force=yes

- name:     Running Docker version
  command:  docker --version
  register: docker_version_out
- assert:
    that:
      - "'Docker' in docker_version_out.stdout"

- name:     Running Docker 'evgenyg/ansible' image
  command:  docker run evgenyg/ansible lsb_release -a
  register: lsb_output
- assert:
    that:
      - "'Ubuntu 14.04' in lsb_output.stdout"
      - "'trusty'       in lsb_output.stdout"

- name:    Generating auto boot script for Docker image '{{ image }}'
  include: auto-boot.yml
  when:    image is defined
