---
etcd: {
  version:  2.0.4, # https://github.com/coreos/etcd/releases
  port:     4001,
  dir_name: etcd-v<version>-linux-amd64,
  url:      '{{ common.urls.github }}/coreos/etcd/releases/download/v<version>/<dir_name>.tar.gz',
  archive:  /opt/etcd-<version>.tar.gz,
  home:     /opt/etcd,
  config:   "{{ ubuntu.etc_default }}/etcd"
}
