---
golang: {
  version: latest, # 1.4.1, latest - https://golang.org/dl/
  latest: {
    command: "curl -Ls '{{ common.urls.golang }}/dl/' | grep '.src.tar.gz' | sed -r 's/<[^>]+>//g' | sed 's/\\.src\\.tar\\.gz//g' | sed -r 's/go//' | awk '{print $1}' | head -1",
    pattern: '^\d+\.\d+'
  },
  url:     'https://storage.googleapis.com/golang/go<version>.linux-amd64.tar.gz',
  archive: /opt/go-<version>.tar.gz,
  path:    /opt/golang,
  home:    /opt/golang/home
}

golang_env: {
  GOPATH: "{{ golang.path }}",
  GOROOT: "{{ golang.home }}/go",
  PATH:   "$PATH:{{ golang.home }}/go/bin",
}
