---
- name: Calculating Go version
  set_fact:
    go_version: "{{ golang.version | calculate( golang.latest ) }}"

- name: Installing Go packages
  apt: name={{ item }}
  with_items:
    - mercurial

- include: "{{ common.utils.download }}"
  vars:
    title:   Golang
    url:     "{{ golang.url     | tokens({ 'version': go_version }) }}"
    archive: "{{ golang.archive | tokens({ 'version': go_version }) }}"
    home:    "{{ golang.home }}"
    clean:   no
    env:     "{{ golang_env }}"
    tests:
      - { run: go version, expect: 'go version go{{ go_version }} ' }
