---
packer: {
  version: latest, # 0.7.5 or latest - https://www.packer.io/downloads.html
  latest: {
    command: "curl -s 'https://dl.bintray.com/mitchellh/packer/' | grep packer | grep linux | tail -1 | cut -d_ -f5",
    pattern: '^\d+\.\d+\.\d+$'
  },
  platform:     amd64, # '386', 'amd64' or 'arm' - http://www.packer.io/downloads.html
  dir:          /opt/packer,
  bin:          /usr/bin/packer,
  download_url: 'https://dl.bintray.com/mitchellh/packer/<version>_linux_<platform>.zip',
  redownload:   false,

  store_aws_credentials: false,

  # AWS credentials: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
  # If 'store_aws_credentials' is true:
    # If true  - loaded from "vars/aws.yml"
    # If false - need to be provided as Ansible extra variables
  load_aws_credentials: false
}
