---
# MySQL playbook for Ubuntu
# http://www.mysql.com/

- name:  MySQL
  hosts: all
  sudo:  yes

  vars_files:
    - vars/common.yml
    - vars/{{ ansible_distribution }}.yml

  roles:
    - { role: run-before, period: daily    }
    - { role: base,       when:   periodic }
    - { role: ansible,    when:   periodic }
    - mysql
    - run-after
