---
# Nexus playbook for Ubuntu
# http://www.sonatype.org/nexus/

- name:  Nexus
  hosts: repo
  sudo:  yes

  vars_files:
    - vars/common.yml
    - vars/{{ ansible_distribution }}.yml

  roles:
    - { role: run-before, period: daily }
    - nexus
    - run-after
