---
ruby: {
  version: latest,  # 2.2.0, latest - https://www.ruby-lang.org/en/downloads/
  installer: 'rvm', # Or 'rbenv'
  latest: {
    command: "curl -Ls '{{ common.urls.ruby }}/en/downloads/' | grep 'The current stable version is' | cut -d' ' -f6 | sed 's/\\.$//'",
    pattern: '^\d+\.\d+\.\d+$'
  },
  gemrc: '/etc/gemrc',
  rvm: {
    url:  'https://get.rvm.io',
    home: /usr/local/rvm
  },
}
